# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

volumes:
  pbft-shared:
  mongodb_data_school:

services:
  b4e-shell-school:
    build:
      context: .
      dockerfile: ../shell/Dockerfile
    image: sawtooth-b4e-shell
    container_name: b4e-shell-school
    volumes:
      - .:/project/sawtooth-b4e

    command: |
      bash -c "
        b4e-protogen
        tail -f /dev/null
      "

    # -------------=== b4e tp   ===-------------
  b4e-tp-5:
    build:
      context: .
      dockerfile: ../processor/Dockerfile
    image: sawtooth-b4e-tp
    container_name: b4e-tp-5
    volumes:
      - '.:/project/sawtooth-b4e'
    depends_on:
      - b4e-shell-school
    command: |
      bash -c "
        sleep 1
        ls
        b4e-tp -v -C tcp://validator-5:4004
        echo b4e-tp-5 connect
      "



  # -------------=== rest api ===-------------

  rest-api-5:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-5
    expose:
      - 8008
    ports:
      - '8058:8008'
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-5:4004 \
          --bind rest-api-5:8008
      "
    stop_signal: SIGKILL


  # -------------=== settings tp ===-------------

  settings-tp-5:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-5
    expose:
      - 4004
    command: settings-tp -C tcp://validator-5:4004
    stop_signal: SIGKILL


  # -------------=== shell ===-------------

  shell-school:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-school
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  # -------------=== validators ===-------------

  validator-5:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-5
    expose:
      - 4004
      - 5050
      - 8800
    ports:
      - '4054:4004'
      - '8805:8800'
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-5.priv ]; then
          echo wait a moment
          cp /pbft-shared/validators/validator-5.pub   /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-5.priv   /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          echo wait a moment
          cp /etc/sawtooth/keys/validator.pub   /pbft-shared/validators/validator-5.pub
          cp /etc/sawtooth/keys/validator.priv   /pbft-shared/validators/validator-5.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://192.168.1.7:8805 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://192.168.1.7:8800 \
          --peers tcp://192.168.1.7:8801 \
          --peers tcp://192.168.1.7:8802 \
          --peers tcp://192.168.1.7:8803 \
          --peers tcp://192.168.1.7:8804 \
      "


  # -------------=== pbft engines ===-------------

  pbft-5:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-5
    command: pbft-engine -vv --connect tcp://validator-5:5050
    stop_signal: SIGKILL

  b4e-rest-api-school:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-b4e-rest-api
    container_name: b4e-rest-api-school
    volumes:
      - .:/project/sawtooth-b4e
    expose:
      - 8000
    ports:
      - '8050:8000'
    depends_on:
      - b4e-shell-school
      - rest-api-5
    command: |
      bash -c "
        b4e-rest-api \
          -B b4e-rest-api-school:8000 \
          -C 192.168.1.7:4054 \
          -R 192.168.1.7:8058 \
          --db-host mongo-school \
          -vv
      "
  b4e-subscriber-school:
    build:
      context: .
      dockerfile: subscriber_b4e/Dockerfile
    image: sawtooth-b4e-subscriber
    container_name: b4e-subscriber_b4e-school
    volumes:
      - '.:/project/sawtooth-b4e'
    depends_on:
      - b4e-shell-school
      - mongo-school
    command: |
      bash -c "
        b4e-subscriber subscribe \
        --db-host mongo-school \
        -C tcp://validator-5:4004 \
        -vv
      "
  mongo-school:
    image: mongo
    container_name: mongo-school
    restart: always
    expose:
      - 27017
    ports:
      - '27019:27017'

    volumes:
      - mongodb_data_school:/data/db
