# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: b4e_environment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='b4e_environment.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x62\x34\x65_environment.proto\"D\n\x0e\x42\x34\x45\x45nvironment\x12\x1a\n\x12institution_number\x18\x01 \x01(\x04\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\";\n\x17\x42\x34\x45\x45nvironmentContainer\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.B4EEnvironmentb\x06proto3')
)




_B4EENVIRONMENT = _descriptor.Descriptor(
  name='B4EEnvironment',
  full_name='B4EEnvironment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='institution_number', full_name='B4EEnvironment.institution_number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='B4EEnvironment.transaction_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=93,
)


_B4EENVIRONMENTCONTAINER = _descriptor.Descriptor(
  name='B4EEnvironmentContainer',
  full_name='B4EEnvironmentContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='B4EEnvironmentContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=154,
)

_B4EENVIRONMENTCONTAINER.fields_by_name['entries'].message_type = _B4EENVIRONMENT
DESCRIPTOR.message_types_by_name['B4EEnvironment'] = _B4EENVIRONMENT
DESCRIPTOR.message_types_by_name['B4EEnvironmentContainer'] = _B4EENVIRONMENTCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

B4EEnvironment = _reflection.GeneratedProtocolMessageType('B4EEnvironment', (_message.Message,), dict(
  DESCRIPTOR = _B4EENVIRONMENT,
  __module__ = 'b4e_environment_pb2'
  # @@protoc_insertion_point(class_scope:B4EEnvironment)
  ))
_sym_db.RegisterMessage(B4EEnvironment)

B4EEnvironmentContainer = _reflection.GeneratedProtocolMessageType('B4EEnvironmentContainer', (_message.Message,), dict(
  DESCRIPTOR = _B4EENVIRONMENTCONTAINER,
  __module__ = 'b4e_environment_pb2'
  # @@protoc_insertion_point(class_scope:B4EEnvironmentContainer)
  ))
_sym_db.RegisterMessage(B4EEnvironmentContainer)


# @@protoc_insertion_point(module_scope)
